image: python:3.8-slim

stages:
  - pre-test
  - basic-download-test
  - feature-test

python-compile-test:
  stage: pre-test
  script:
    # Check whether script is syntax error free
    - python3 -m py_compile vo-scraper.py

ensure-same-version:
  stage: pre-test
  script:
    # Ensure verion numbers in `VERSION` and `vo-scraper.py` match
    - grep -q $(sed -n "s/^.*program_version = '\(.*\)'$/\1/p" vo-scraper.py) VERSION

# Download unprotected video
unprotected-recording:
  stage: basic-download-test
  needs: [python-compile-test]
  script:
    # Install dependency
    - pip3 install requests
    # Download video
    - python3 vo-scraper.py --quality low --latest https://video.ethz.ch/lectures/d-infk/2020/spring/252-0028-00L.html
    # Compare checksums
    - echo $(sha1sum Lecture\ Recordings/Digital\ Design\ and\ Computer\ Architecture/2020-03-12_low-3ebf562d.mp4) | grep -q f80bcc1c215cebf64a4da7f9623406fb1309e512

# Download 'PWD' protected video
pwd-protected-recording:
  stage: basic-download-test
  needs: [python-compile-test]
  script:
    # Install dependency
    - pip3 install requests
    # Download video
    - python3 vo-scraper.py --quality low --latest --file $PWD_LINK_FILE
    # Compare checksums
    - echo $(sha1sum Lecture\ Recordings/Introduction\ to\ Machine\ Learning/2020-05-27\ -\ Tutorial_low-1898f0cc.mp4) | grep -q dce9f9aeb00693b6dbce49b113c10d2f84a29b70

# Download 'ETH' protected video
eth-protected-recording:
  stage: basic-download-test
  needs: [python-compile-test]
  script:
    # Install dependency
    - pip3 install requests
    # Download video
    - python3 vo-scraper.py --quality low --latest --file $ETH_LINK_FILE
    # Compare checksums
    - echo $(sha1sum Lecture\ Recordings/Advanced\ Systems\ Lab/2020-03-19_low-fd29952f.mp4) | grep -q efd4a1779a29da08c0186ed6121fc10bfa7e8e83

# Test default named parameter file
default-parameter-file:
  stage: feature-test
  needs: [unprotected-recording]
  script:
    # Install dependency
    - pip3 install requests
    # Add parameter file
    - printf -- "--quality low\n--latest\n" > parameters.txt
    # Download video
    - python3 vo-scraper.py https://video.ethz.ch/lectures/d-infk/2020/spring/252-0028-00L.html
    # Compare checksums
    - echo $(sha1sum Lecture\ Recordings/Digital\ Design\ and\ Computer\ Architecture/2020-03-12_low-3ebf562d.mp4) | grep -q f80bcc1c215cebf64a4da7f9623406fb1309e512

# Test custom named parameter file
custom-parameter-file:
  stage: feature-test
  needs: [unprotected-recording]
  script:
    # Install dependency
    - pip3 install requests
    # Add parameter file
    - printf -- "--quality low\n--latest\n" > parameters2.txt
    # Download video
    - python3 vo-scraper.py --parameter-file parameters2.txt https://video.ethz.ch/lectures/d-infk/2020/spring/252-0028-00L.html
    # Compare checksums
    - echo $(sha1sum Lecture\ Recordings/Digital\ Design\ and\ Computer\ Architecture/2020-03-12_low-3ebf562d.mp4) | grep -q f80bcc1c215cebf64a4da7f9623406fb1309e512
