image: python:3.8-slim

stages:
  - pre-test
  - tests

python-compile-test:
  stage: pre-test
  script:
    # Check whether script is syntax error free
    - python3 -m py_compile vo-scraper.py

ensure-same-version:
  stage: pre-test
  script:
    # Ensure verion numbers in `VERSION` and `vo-scraper.py` match
    - grep -q $(sed -n "s/^.*program_version = '\(.*\)'$/\1/p" vo-scraper.py) VERSION

# Download unprotected video
unprotected-recording:
  stage: tests
  needs: [python-compile-test]
  script:
    # Install dependency
    - pip3 install requests
    # Download video
    - python3 vo-scraper.py --quality low --latest https://video.ethz.ch/lectures/d-infk/2020/spring/252-0028-00L.html
    # Compare checksums
    - echo $(sha1sum Lecture\ Recordings/Digital\ Design\ and\ Computer\ Architecture/2020-03-12_low-3ebf562d.mp4) | grep -q f80bcc1c215cebf64a4da7f9623406fb1309e512
