name: vo-scraper ci

on:
  push:
  pull_request:

jobs:
  python-compile-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Python Compile Test
        run: python3 -m py_compile vo-scraper.py

  ensure-same-version:
    runs-on: ubuntu-latest
    needs: python-compile-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ensure Same Version
        run: grep -q $(sed -n "s/^.*program_version = '\(.*\)'$/\1/p" vo-scraper.py) VERSION
